# --------------------------------------------
# dein
# --------------------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

# --------------------------------------------
# ディレクトリをTreeで表示
# --------------------------------------------
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.config/nvim/dein_tomls/nerdtree.vim'
# [[plugins]]
# repo = 'jistr/vim-nerdtree-tabs'
# hook_add = 'source ~/.config/nvim/dein_tomls/nerdtree-tabs.vim'

# --------------------------------------------
# fzf-vim
# --------------------------------------------
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'source ~/.config/nvim/dein_tomls/fzf.vim'

# --------------------------------------------
# tomlファイルをハイライト
# --------------------------------------------
[[plugins]]
repo = 'cespare/vim-toml'

# --------------------------------------------
# ctrl+-でコメントアウト
# --------------------------------------------
[[plugins]]
repo = 'tomtom/tcomment_vim'

# --------------------------------------------
# GitコマンドをVim上で実行
# --------------------------------------------
[[plugins]]
repo = 'tpope/vim-fugitive'

# --------------------------------------------
# ステータスライン
# --------------------------------------------
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/.config/nvim/dein_tomls/vim-airline.vim'

# --------------------------------------------
# Scriptをその場で実行
# --------------------------------------------
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.config/nvim/dein_tomls/vim-quickrun.vim'

# --------------------------------------------
# 囲い文字を入れ替える
# --------------------------------------------
[[plugins]]
repo = 'tpope/vim-surround'

# --------------------------------------------
# Emmet
# --------------------------------------------
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = 'source ~/.config/nvim/dein_tomls/emmet-vim.vim'

# --------------------------------------------
# Denite
# --------------------------------------------
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.config/nvim/dein_tomls/denite.vim'

# --------------------------------------------
# Denite-Gtags
# --------------------------------------------
[[plugins]]
repo = 'ozelentok/denite-gtags'
hook_add = 'source ~/.config/nvim/dein_tomls/denite-gtags.vim'

# --------------------------------------------
# gtags,ctagsを自動生成
# --------------------------------------------
[[plugins]]
repo = 'jsfaint/gen_tags.vim'
hook_add = 'source ~/.config/nvim/dein_tomls/gen_tags.vim'

# --------------------------------------------
# リアルタイムLinter
# --------------------------------------------
[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.config/nvim/dein_tomls/ale.vim'

# --------------------------------------------
# 画面分割時の画面大きさ変更キーなど連続で打つコマンドを楽にする
# --------------------------------------------
[[plugins]]
repo = 'kana/vim-submode'
hook_add = 'source ~/.config/nvim/dein_tomls/vim-submode.vim'

# --------------------------------------------
# Golang開発環境
# --------------------------------------------
[[plugins]]
repo = 'fatih/vim-go'
hook_add = 'source ~/.config/nvim/dein_tomls/vim-go.vim'

# --------------------------------------------
# 好きな文字でインデントを揃える
# --------------------------------------------
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = 'source ~/.config/nvim/dein_tomls/vim-easy-align.vim'

# --------------------------------------------
# plantuml
# --------------------------------------------
[[plugins]]
repo = 'aklt/plantuml-syntax'

# --------------------------------------------
# markdownプレビュー
# --------------------------------------------
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build =  'cd app & yarn install' 

# --------------------------------------------
# PHPコードチェック、未使用変数のハイライト
# --------------------------------------------
[[plugins]]
repo = 'flyinshadow/php_localvarcheck.vim'
hook_add = 'source ~/.config/nvim/dein_tomls/php_localvarcheck.vim'

# --------------------------------------------
# Typscript IDE
# --------------------------------------------
[[plugins]]
repo = 'Quramy/tsuquyomi'

# --------------------------------------------
# Typscriptシンタックスハイライト
# --------------------------------------------
[[plugins]]
repo = 'leafgarland/typescript-vim'

# --------------------------------------------
# JS/TSインデント
# --------------------------------------------
[[plugins]]
repo = 'jason0x43/vim-js-indent'

# --------------------------------------------
# phpDocコメント生成
# --------------------------------------------
[[plugins]]
repo = 'vim-scripts/PDV--phpdocumentor-for-vim'
hook_add = 'source ~/.config/nvim/dein_tomls/PDV--phpdocumentor-for-vim.vim'

# --------------------------------------------
# dein
# --------------------------------------------
# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# hook_add = 'source ~/.config/nvim/dein_tomls/deoplete.vim'

# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'
# hook_add = 'source ~/.config/nvim/dein_tomls/neosnippet-snippets.vim'
#

# --------------------------------------------
# GitBlamer
# --------------------------------------------
[[plugins]]
repo = 'rhysd/git-messenger.vim'
hook_add = 'source ~/.config/nvim/dein_tomls/git-messenger.vim'

# --------------------------------------------
# coc - 入力補完
# --------------------------------------------
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = 'source ~/.config/nvim/dein_tomls/coc.vim'

# --------------------------------------------
# ultisnips - Snipets
# --------------------------------------------
[[plugins]]
repo = 'SirVer/ultisnips'

# --------------------------------------------
# vim-snippets - Snipetsファイル
# --------------------------------------------
[[plugins]]
repo = 'honza/vim-snippets'

# --------------------------------------------
# firenvim - ブラウザでNeoVim
# --------------------------------------------
[[plugins]]
repo = 'glacambre/firenvim'
hook_add = 'source ~/.config/nvim/dein_tomls/firenvim.vim'
hook_post_update = '''
  call firenvim#install(0)
'''

# --------------------------------------------
# gitの差分を+ - で表示
# --------------------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/.config/nvim/dein_tomls/vim-gitgutter.vim'

[[plugins]]
repo = 'maksimr/vim-jsbeautify'

