#!/usr/bin/env bash

#
## リポジトリ内の.git/hooksがある場合はそちらを優先するためのスクリプト
#
GIT_ROOT=`git rev-parse --show-superproject-working-tree --show-toplevel | head -1`
HOOK_NAME=`basename $0`
LOCAL_HOOK="${GIT_ROOT}/.git/hooks/${HOOK_NAME}"

if [ -e $LOCAL_HOOK ]; then
  # .git/hooks/pre-commitで`dirname`が使われている場合、本スクリプトのディレクトリを指してしまうため、
  # リポジトリのPATHを指すようにする
  dirname() {
    echo $GIT_ROOT/.git/hooks
  }
  source $LOCAL_HOOK
  exit
fi
