#!/usr/bin/env bash
words=(
    console.log
    var_dump
    outer_log
)
files=($(git diff --cached --name-only HEAD))
error=0
for file in "${files[@]}"
do
    for word in ${words[@]}
    do
        if grep "$word" $file >/dev/null; then
            echo $file
            grep --color -n "$word" $file
            error=1
        fi
    done
done

if [ $error -eq 1 ]; then
    printf "\e[31;1m\nDebug sentence is exist!\nIf you want to continue, exec \`git commit --no-verify\`\e[m\n"
    exit 1
fi
