#!/usr/bin/env bash

# リポジトリ内の.git/hooksがある場合はそちらを優先する
source ~/dotfiles/terminal/git/hooks/_load_local_hook

jiraNo=$(git branch --show-current | grep -oP '[0-9]*' | head -n 1)
firstLine=$(head -n1 $1)  # git commit --amendとの区別のために最初の一行を取得

test -z "$jiraNo" && exit

if [ -z "$firstLine" ] ;then  # 一行目が空行であれば（--amendでなければ）以下を実行
  : # gsed -i "1s/^/${jiraNo}/" $1
fi
