- block:
  - block: 
    - name: Install npm packages
      npm:
        name: "{{ item }}"
        global: yes
      with_items: "{{ npm_packages }}"
    tags:
      - npm

  - block: 
    - name: Set pyenv python2 for neovim
      shell: pyenv install 2.7.15 && pyenv virtualenv 2.7.13 neovim2 && pyenv activate neovim2 && pip2 install neovim
      become: yes
      changed_when: false

    - name: Set pyenv python3 for neovim
      shell: pyenv install 3.5.3 && pyenv virtualenv 3.5.3 neovim3 && pyenv activate neovim3 && pip install neovim
      # @see https://qiita.com/hisa_shim/items/abb4936f1f676fe6a7b8
      # deniteは3.6.1以上じゃないとだめ
      # CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix bzip2)/include -I$(brew --prefix readline)/include -I$(xcrun --show-sdk-path)/usr/include" LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib -L$(brew --prefix zlib)/lib -L$(brew --prefix bzip2)/lib" pyenv install --patch 3.6.2 < <(curl -sSL https://github.com/python/cpython/commit/8ea6353.patch\?full_index\=1)
      become: yes
      changed_when: false

    - name: Install pip
      shell: easy_install pip
      become: yes
      changed_when: false

    - name: Install Neovim by pip
      shell: pip install neovim
      changed_when: false

    - name: Install Neovim by pip3
      shell: pip3 install neovim
      changed_when: false

    - name: Install PythonProvider by pip3
      shell: pip3 install pynvim
      changed_when: false

    - name: Download dein
      get_url: 
        url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh 
        dest: ~/.config/nvim/

    - name: Install dein
      shell: sh ~/.config/nvim/installer.sh ~/.config/nvim/dein
      changed_when: false

    - name: Refresh SystemUIServer for screencapture
      shell: killall SystemUIServer
      become: yes
      changed_when: false

  tags:
    - shell_command
