# --------------------------------------------
# dein
# --------------------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

# --------------------------------------------
# fzf-vim
# --------------------------------------------
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/fzf.vim'
lazy = 0

# --------------------------------------------
# コメントアウト
# --------------------------------------------
[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = 'source ~/.config/nvim/plugin_settings/nerdcommenter.vim'
lazy = 0

# --------------------------------------------
# GitコマンドをVim上で実行
# --------------------------------------------
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-fugitive.vim'
lazy = 0

# --------------------------------------------
# ステータスライン
# --------------------------------------------
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-airline.vim'
lazy = 0

# --------------------------------------------
# Scriptをその場で実行
# --------------------------------------------
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-quickrun.vim'
lazy = 1

# --------------------------------------------
# Emmet
# --------------------------------------------
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = 'source ~/.config/nvim/plugin_settings/emmet-vim.vim'
lazy = 0

# --------------------------------------------
# リアルタイムLinter
# --------------------------------------------
[[plugins]]
repo = 'w0rp/ale'
on_event = 'BufRead'
hook_add = 'source ~/.config/nvim/plugin_settings/ale.vim'
lazy = 1

# --------------------------------------------
# 画面分割時の画面大きさ変更キーなど連続で打つコマンドを楽にする
# --------------------------------------------
[[plugins]]
repo = 'kana/vim-submode'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-submode.vim'
lazy = 0

# --------------------------------------------
# 好きな文字でインデントを揃える
# --------------------------------------------
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-easy-align.vim'
lazy = 1

# --------------------------------------------
# plantuml
# --------------------------------------------
[[plugins]]
repo = 'aklt/plantuml-syntax'
lazy = 1

# --------------------------------------------
# PHPコードチェック、未使用変数のハイライト
# --------------------------------------------
# [[plugins]]
# repo = 'flyinshadow/php_localvarcheck.vim'
# hook_add = 'source ~/.config/nvim/plugin_settings/php_localvarcheck.vim'

# --------------------------------------------
# JavaScript整形
# --------------------------------------------
[[plugins]]
repo = 'maksimr/vim-jsbeautify'
lazy = 1

# --------------------------------------------
# GitBlamer
# --------------------------------------------
[[plugins]]
repo = 'rhysd/git-messenger.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/git-messenger.vim'
lazy = 1

# --------------------------------------------
# coc - 入力補完
# --------------------------------------------
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = 'source ~/.config/nvim/plugin_settings/coc.vim'
lazy = 0

# --------------------------------------------
# vim-snippets - Snipets定義ファイル
# 様々なsnippetsファイルが用意されているプラグイン
# ~/.config/nvim/dein/repos/github.com/honza/vim-snippets/で参照可能
# --------------------------------------------
[[plugins]]
repo = 'honza/vim-snippets'
lazy = 1

# --------------------------------------------
# gitの差分を+ - で表示
# --------------------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter'
lazy = 0
# hook_add = 'source ~/.config/nvim/plugin_settings/vim-gitgutter.vim'

# --------------------------------------------
# Debugger
# --------------------------------------------
[[plugins]]
repo = 'vim-vdebug/vdebug'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-vdebug.vim'
on_ft = ['php']
lazy = 1

# --------------------------------------------
# Swift - シンタックスハイライト
# --------------------------------------------
[[plugins]]
repo = 'keith/swift.vim'
on_ft = ['swift']
lazy = 1

# --------------------------------------------
# カラーコードプレビュー
# --------------------------------------------
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'
lazy = 0

# --------------------------------------------
# 一行ステートメントを複数行ステートメントにする
# --------------------------------------------
[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/splitjoin.vim'
lazy = 1

# --------------------------------------------
# 翻訳
# --------------------------------------------
[[plugins]]
repo = 'skanehira/translate.vim'
lazy = 1

# --------------------------------------------
# terraform
# --------------------------------------------
[[plugins]]
repo = 'hashivim/vim-terraform'
hook_add = 'source ~/.config/nvim/plugin_settings/terraform.vim'
on_ft = ['terraform']
lazy = 1

# --------------------------------------------
# terraform-completion
# --------------------------------------------
[[plugins]]
repo = 'juliosueiras/vim-terraform-completion'
on_ft = ['terraform']
lazy = 1

# --------------------------------------------
# コード画像化
# --------------------------------------------
[[plugins]]
repo = 'segeljakt/vim-silicon'
hook_add = 'source ~/.config/nvim/plugin_settings/silicon.vim'
lazy = 0

# --------------------------------------------
# tree-sitter
# --------------------------------------------
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = 'source ~/.config/nvim/plugin_settings/tree-sitter.vim'
lazy = 1

# --------------------------------------------
# vim-sandwich
# --------------------------------------------
[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = 'source ~/.config/nvim/plugin_settings/sandwich.vim'
lazy = 0

# --------------------------------------------
# fern - ファイルツリー
# --------------------------------------------
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/fern.vim'
lazy = 0

# --------------------------------------------
# fern preview
# --------------------------------------------
[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/fern-preview.vim'
lazy = 0

# --------------------------------------------
# template
# --------------------------------------------
# [[plugins]]
# repo = ''
# hook_add = 'source ~/.config/nvim/plugin_settings/'
# lazy = 1
