# --------------------------------------------
# dein
# --------------------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

# --------------------------------------------
# ディレクトリをTreeで表示
# --------------------------------------------
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.config/nvim/plugin_settings/nerdtree.vim'
# [[plugins]]
# repo = 'jistr/vim-nerdtree-tabs'
# hook_add = 'source ~/.config/nvim/plugin_settings/nerdtree-tabs.vim'

# --------------------------------------------
# fzf-vim
# --------------------------------------------
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/fzf.vim'

# --------------------------------------------
# tomlファイルをハイライト
# --------------------------------------------
[[plugins]]
repo = 'cespare/vim-toml'

# --------------------------------------------
# ctrl+-でコメントアウト
# --------------------------------------------
[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = 'source ~/.config/nvim/plugin_settings/tcomment.vim'

# --------------------------------------------
# GitコマンドをVim上で実行
# --------------------------------------------
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-fugitive.vim'

# --------------------------------------------
# ステータスライン
# --------------------------------------------
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-airline.vim'

# --------------------------------------------
# Scriptをその場で実行
# --------------------------------------------
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-quickrun.vim'

# --------------------------------------------
# 囲い文字を入れ替える
# --------------------------------------------
[[plugins]]
repo = 'tpope/vim-surround'

# --------------------------------------------
# Emmet
# --------------------------------------------
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = 'source ~/.config/nvim/plugin_settings/emmet-vim.vim'

# --------------------------------------------
# Denite
# --------------------------------------------
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.config/nvim/plugin_settings/denite.vim'

# --------------------------------------------
# Denite-Gtags
# --------------------------------------------
[[plugins]]
repo = 'ozelentok/denite-gtags'
hook_add = 'source ~/.config/nvim/plugin_settings/denite-gtags.vim'

# --------------------------------------------
# gtags,ctagsを自動生成
# --------------------------------------------
[[plugins]]
repo = 'jsfaint/gen_tags.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/gen_tags.vim'

# --------------------------------------------
# リアルタイムLinter
# --------------------------------------------
[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.config/nvim/plugin_settings/ale.vim'

# --------------------------------------------
# 画面分割時の画面大きさ変更キーなど連続で打つコマンドを楽にする
# --------------------------------------------
[[plugins]]
repo = 'kana/vim-submode'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-submode.vim'

# --------------------------------------------
# Golang開発環境
# --------------------------------------------
[[plugins]]
repo = 'fatih/vim-go'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-go.vim'

# --------------------------------------------
# 好きな文字でインデントを揃える
# --------------------------------------------
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-easy-align.vim'

# --------------------------------------------
# plantuml
# --------------------------------------------
[[plugins]]
repo = 'aklt/plantuml-syntax'

# --------------------------------------------
# markdownプレビュー
# --------------------------------------------
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build =  'cd app & yarn install' 

# --------------------------------------------
# PHPコードチェック、未使用変数のハイライト
# --------------------------------------------
[[plugins]]
repo = 'flyinshadow/php_localvarcheck.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/php_localvarcheck.vim'

# --------------------------------------------
# Typscript IDE
# filetypeを勝手に変えてしまい、vim-fzfでtsxを開くとtypescriptreactで
# 認識されてハイライトが効かなくなってしまうため、コメントアウト
# --------------------------------------------
# [[plugins]]
# repo = 'Quramy/tsuquyomi'

# --------------------------------------------
# Typscriptシンタックスハイライト
# --------------------------------------------
[[plugins]]
repo = 'leafgarland/typescript-vim'

# --------------------------------------------
# TypscriptReactシンタックスハイライト
# --------------------------------------------
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

# --------------------------------------------
# JavaScriptハイライト
# --------------------------------------------
[[plugins]]
repo = 'pangloss/vim-javascript'

# --------------------------------------------
# JS/TSインデント
# --------------------------------------------
[[plugins]]
repo = 'jason0x43/vim-js-indent'

# --------------------------------------------
# JavaScript整形
# --------------------------------------------
[[plugins]]
repo = 'maksimr/vim-jsbeautify'


# --------------------------------------------
# GitBlamer
# --------------------------------------------
[[plugins]]
repo = 'rhysd/git-messenger.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/git-messenger.vim'

# --------------------------------------------
# coc - 入力補完
# --------------------------------------------
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = 'source ~/.config/nvim/plugin_settings/coc.vim'

# --------------------------------------------
# ultisnips - Snipets
# Snipetsを使うためのプラグイン
# 独自のsnippetsファイルはvim-snippetsではなくここで記述する
# --------------------------------------------
[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = 'source ~/.config/nvim/plugin_settings/ultisnips.vim'

# --------------------------------------------
# vim-snippets - Snipets定義ファイル
# 様々なsnippetsファイルが用意されているプラグイン
# ~/.config/nvim/dein/repos/github.com/honza/vim-snippets/で参照可能
# --------------------------------------------
[[plugins]]
repo = 'honza/vim-snippets'

# --------------------------------------------
# firenvim - ブラウザでNeoVim
# --------------------------------------------
[[plugins]]
repo = 'glacambre/firenvim'
hook_add = 'source ~/.config/nvim/plugin_settings/firenvim.vim'
hook_post_update = '''
  call firenvim#install(0)
'''

# --------------------------------------------
# gitの差分を+ - で表示
# --------------------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter'
# hook_add = 'source ~/.config/nvim/plugin_settings/vim-gitgutter.vim'

