# --------------------------------------------
# dein
# --------------------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

# --------------------------------------------
# fzf-vim
# --------------------------------------------
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/fzf.vim'

# --------------------------------------------
# コメントアウト
# --------------------------------------------
[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = 'source ~/.config/nvim/plugin_settings/nerdcommenter.vim'

# --------------------------------------------
# GitコマンドをVim上で実行
# --------------------------------------------
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-fugitive.vim'

# --------------------------------------------
# ステータスライン
# --------------------------------------------
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-airline.vim'

# --------------------------------------------
# Scriptをその場で実行
# --------------------------------------------
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-quickrun.vim'

# --------------------------------------------
# Emmet
# --------------------------------------------
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = 'source ~/.config/nvim/plugin_settings/emmet-vim.vim'

# --------------------------------------------
# Denite
# --------------------------------------------
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.config/nvim/plugin_settings/denite.vim'

# --------------------------------------------
# Denite-Gtags
# --------------------------------------------
[[plugins]]
repo = 'ozelentok/denite-gtags'
hook_add = 'source ~/.config/nvim/plugin_settings/denite-gtags.vim'

# --------------------------------------------
# gtags,ctagsを自動生成
# --------------------------------------------
# [[plugins]]
# repo = 'jsfaint/gen_tags.vim'
# hook_add = 'source ~/.config/nvim/plugin_settings/gen_tags.vim'

# --------------------------------------------
# リアルタイムLinter
# --------------------------------------------
[[plugins]]
repo = 'w0rp/ale'
on_event = 'BufRead'
hook_add = 'source ~/.config/nvim/plugin_settings/ale.vim'

# --------------------------------------------
# 画面分割時の画面大きさ変更キーなど連続で打つコマンドを楽にする
# --------------------------------------------
[[plugins]]
repo = 'kana/vim-submode'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-submode.vim'

# --------------------------------------------
# Golang開発環境
# --------------------------------------------
[[plugins]]
repo = 'fatih/vim-go'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-go.vim'

# --------------------------------------------
# 好きな文字でインデントを揃える
# --------------------------------------------
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-easy-align.vim'

# --------------------------------------------
# plantuml
# --------------------------------------------
[[plugins]]
repo = 'aklt/plantuml-syntax'

# --------------------------------------------
# markdownプレビュー
# --------------------------------------------
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build =  'cd app & yarn install'

# --------------------------------------------
# PHPコードチェック、未使用変数のハイライト
# --------------------------------------------
# [[plugins]]
# repo = 'flyinshadow/php_localvarcheck.vim'
# hook_add = 'source ~/.config/nvim/plugin_settings/php_localvarcheck.vim'

# --------------------------------------------
# JavaScript整形
# --------------------------------------------
[[plugins]]
repo = 'maksimr/vim-jsbeautify'

# --------------------------------------------
# GitBlamer
# --------------------------------------------
[[plugins]]
repo = 'rhysd/git-messenger.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/git-messenger.vim'

# --------------------------------------------
# coc - 入力補完
# --------------------------------------------
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = 'source ~/.config/nvim/plugin_settings/coc.vim'

# --------------------------------------------
# vim-snippets - Snipets定義ファイル
# 様々なsnippetsファイルが用意されているプラグイン
# ~/.config/nvim/dein/repos/github.com/honza/vim-snippets/で参照可能
# --------------------------------------------
[[plugins]]
repo = 'honza/vim-snippets'

# --------------------------------------------
# firenvim - ブラウザでNeoVim
# --------------------------------------------
# [[plugins]]
# repo = 'glacambre/firenvim'
# hook_add = 'source ~/.config/nvim/plugin_settings/firenvim.vim'
# hook_post_update = '''
#   call firenvim#install(0)
# '''

# --------------------------------------------
# gitの差分を+ - で表示
# --------------------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter'
# hook_add = 'source ~/.config/nvim/plugin_settings/vim-gitgutter.vim'

# --------------------------------------------
# Debugger
# --------------------------------------------
[[plugins]]
repo = 'vim-vdebug/vdebug'
hook_add = 'source ~/.config/nvim/plugin_settings/vim-vdebug.vim'

# --------------------------------------------
# Swift - シンタックスハイライト
# --------------------------------------------
[[plugins]]
repo = 'keith/swift.vim'

# --------------------------------------------
# カラーコードプレビュー
# --------------------------------------------
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

# --------------------------------------------
# 共同編集
# --------------------------------------------
# [[plugins]]
# repo = 'jbyuki/instant.nvim'
# hook_add = 'source ~/.config/nvim/plugin_settings/instant.vim'

# --------------------------------------------
# 一行ステートメントを複数行ステートメントにする
# --------------------------------------------
[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/splitjoin.vim'

# --------------------------------------------
# 翻訳
# --------------------------------------------
[[plugins]]
repo = 'skanehira/translate.vim'

# --------------------------------------------
# 禅モード
# --------------------------------------------
[[plugins]]
repo = 'junegunn/goyo.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/goyo.vim'

# --------------------------------------------
# 段落フォーカス
# --------------------------------------------
[[plugins]]
repo = 'junegunn/limelight.vim'

# --------------------------------------------
# terraform
# --------------------------------------------
[[plugins]]
repo = 'hashivim/vim-terraform'
hook_add = 'source ~/.config/nvim/plugin_settings/terraform.vim'

# --------------------------------------------
# terraform-completion
# --------------------------------------------
[[plugins]]
repo = 'juliosueiras/vim-terraform-completion'

# --------------------------------------------
# コード画像化
# --------------------------------------------
[[plugins]]
repo = 'segeljakt/vim-silicon'
hook_add = 'source ~/.config/nvim/plugin_settings/silicon.vim'

# --------------------------------------------
# tree-sitter
# --------------------------------------------
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = 'source ~/.config/nvim/plugin_settings/tree-sitter.vim'

# --------------------------------------------
# vim-sandwich
# --------------------------------------------
[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = 'source ~/.config/nvim/plugin_settings/sandwich.vim'

# --------------------------------------------
# fern - ファイルツリー
# --------------------------------------------
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/fern.vim'

# --------------------------------------------
# fern preview
# --------------------------------------------
[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
hook_add = 'source ~/.config/nvim/plugin_settings/fern-preview.vim'

# --------------------------------------------
# vim-swap
# --------------------------------------------
[[plugins]]
repo = 'machakann/vim-swap'
