packages:
  - name: google-chrome
  - name: firefox
  - name: google-japanese-ime
  - name: visual-studio-code
  - name: iterm2
  - name: hyper
  - name: docker
  - name: wireshark
  - name: virtualbox
  - name: sequel-ace
  - name: ngrok
  - name: java11
  - name: couleurs
  - name: keycastr
  - name: another-redis-desktop-manager
  - name: font-hackgen
  - name: font-hackgen-nerd

