- block:

  - name: homebrew cask packages install 'item.name'
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
    homebrew_cask:
      name: '{{ item.name }}'
      state: "{{ item.state | default('present') }}"
    with_items: '{{ packages }}'

  tags:
    - homebrew_cask
