settings:
  - { domain: com.apple.iphonesimulator, key: AllowFullscreenMode, type: bool, value: TRUE }
  - { domain: com.apple.iphonesimulator, key: ShowSingleTouches, type: bool, value: TRUE }
  - { domain: com.apple.finder, key: QuitMenuItem, type: bool, value: TRUE }
files:
  # Zsh
  - { src: ~/dotfiles/zsh/zshrc, dest: ~/.zshrc }
  # Terminal
  - { src: ~/dotfiles/terminal/tmux.conf, dest: ~/.tmux.conf }
  - { src: ~/dotfiles/terminal/hyper.js, dest: ~/.hyper.js }
  - { src: ~/dotfiles/terminal/agignore, dest: ~/.agignore }
  - { src: ~/dotfiles/terminal/gitconfig, dest: ~/.gitconfig }
  - { src: ~/dotfiles/terminal/gitignore_global, dest: ~/.gitignore_global }
  - { src: ~/dotfiles/terminal/git_template, dest: ~/.git_template }
  # Vim
  - { src: ~/dotfiles/vim/xvimrc, dest: ~/.xvimrc }
  - { src: ~/dotfiles/vim/init.vim, dest: ~/.vimrc }
  - { src: ~/dotfiles/vim/init.vim, dest: ~/.config/nvim/init.vim }
  - { src: ~/dotfiles/vim/dein.toml, dest: ~/.config/nvim/dein.toml }
  - { src: ~/dotfiles/vim/plugin_settings, dest: ~/.config/nvim/plugin_settings }
  - { src: ~/dotfiles/vim/coc/coc-settings.json, dest: ~/.config/nvim/coc-settings.json }
  - { src: ~/dotfiles/vim/coc/package.json, dest: ~/.config/coc/extensions/package.json }
  - { src: ~/dotfiles/vim/UltiSnips, dest: ~/.config/nvim/UltiSnips }
