- block:

  - block:
    - name: set osx defaults
      osx_defaults:
        domain: "{{ item.domain }}"
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      with_items: "{{ settings }}"
    tags:
      - osx_defaults

  - block:
    - name: set symbolic link
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items: "{{ files }}"
    tags:
      - symbolic_link

  - block:
    - name: make directories
      file:
        path: "{{ item.path }}"
        state: directory
      with_items: "{{ directories }}"
    tags:
      - directories

  - block:
    - name: change mode
      file:
        path: "{{ item.path }}"
        mode: "{{ item.mode }}"
      with_items: "{{ modes }}"
    tags:
      - change_mode

  - block:
    - name: remove files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ removes }}"
    tags:
      - remove_files

  tags:
    - macos
