# PATHがsource ~/.zshrcする度に重複して登録されないようにする
typeset -U path PATH

source_file() {
  [ -n "$1" ] && [ -f $1 ] && source $1
}

source_file ~/dotfiles/zsh/settings.zsh
source_file ~/dotfiles/zsh/exports.zsh
source_file ~/dotfiles/zsh/alias.zsh
source_file ~/dotfiles/zsh/function.zsh
source_file ~/.phpbrew/bashrc
