# PATHがsource ~/.zshrcする度に重複して登録されないようにする
typeset -U path PATH
alias vim='nvim'

source_file() {
    [ -n "$1" ] && [ -f $1 ] && source $1
}

source_file ~/dotfiles/zsh/settings.zsh
source_file ~/dotfiles/zsh/exports.zsh
source_file ~/dotfiles/zsh/function.zsh
source_file ~/dotfiles/zsh/alias_script.zsh
source_file ~/dotfiles/zsh/alias_command.zsh
source_file ~/dotfiles/zsh/alias_function.zsh
source_file ~/.phpbrew/bashrc
# zshrc.localを読み込む(行末に書くことで設定を上書きする)
source_file ~/.zshrc.local

